# Automatically migrated from legacy .beetsconfig.
# https://beets.readthedocs.org/en/latest/reference/config.html

library: /home/wagner/.config/beets/music-library.blb
directory: /mnt/music

import:
    copy: true
    write: true
    delete: true
    resume: ask
    incremental: false
    art: true
    quiet_fallback: skip
    timid: false
    log: /home/wagner/.config/beets/import.log
ignore: .* *~

replace:
    '[\\/\?"]': _
    '["\*<>\|]|\s+$': _
    # Remove these chars
    "[ .!,()':]+": _
    # Remove multiple brackets
    '\[+|\]+': _
    # Merge duplicated underscores
    '_+': _
    # Remove underscores in the beginning
    '^_+': ''
    # Remove underscores in the end
    '_+$': ''
    # Change the equal sign in the beginning
    '^=+': '.'

clutter:
    - Thumbs.DB
    - .DS_Store
    - cover.jpg

color: yes

id3v23: yes

paths:
    comp: listen/$bpm/=compilations/${original_or_recording_year}_$album%aunique{}/${disc_and_track} ${compilation_artist}${title}
    singleton: listen/$bpm/=songs/$artist - $title
    # VA_$genre/
    grouping:@: ipod/playlists/${grouping}/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:1: ipod/lib/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:2: ipod/lib/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:3: ipod/lib/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:4: ipod/lib/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:5: out/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:6: out/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:7: out/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:8: out/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    bpm:9: out/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}
    default: listen/$bpm/${albumartist}/${original_or_recording_year}_${album}/${disc_and_track} ${compilation_artist}${title}

####################################################################################################

plugins:
    - inline # http://beets.readthedocs.org/en/latest/plugins/inline.html
    - info # http://beets.readthedocs.org/en/latest/plugins/info.html
    - random # http://beets.readthedocs.org/en/latest/plugins/random.html
    - discogs # http://beets.readthedocs.org/en/latest/plugins/discogs.html
    - lastgenre # http://beets.readthedocs.org/en/latest/plugins/lastgenre.html
    - embedart # https://beets.readthedocs.org/en/latest/plugins/embedart.html
    - fetchart # https://beets.readthedocs.org/en/latest/plugins/fetchart.html
    - lyrics # https://beets.readthedocs.org/en/latest/plugins/lyrics.html
    - missing # http://beets.readthedocs.org/en/latest/plugins/missing.html
    - duplicates # http://beets.readthedocs.org/en/latest/plugins/duplicates.html
    - mpdupdate # http://beets.readthedocs.org/en/latest/plugins/mpdupdate.html

item_fields:
    disc_and_track: u'%02i%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
    compilation_artist: u'%s - ' % (artist) if comp else u''
    original_or_recording_year: original_year if original_year else year

embedart:
    #auto: no
    maxwidth: 200

fetchart:
    #cautious: true
    cover_names: front back
    remote_priority: true

lyrics:
    fallback: 'No lyrics found'

lastgenre:
    canonical: ''
    source: track
    count: 3

mpd:
    host: localhost
    port: 6600
