# https://docs.travis-ci.com/user/reference/xenial/
dist: xenial
cache:
  npm: true
  directories:
    - $HOME/.cache/pip
# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
  - "3.7"
script:
  # Run some of the pre-commit hooks on Travis.
  # Running "pre-commit run --all-files" checks more files than expected;
  # e.g. it doesn't respect flake8's exclude config on setup.cfg.
  - black --check .
  - flake8
install:
  - npm install -g semantic-release@15 @semantic-release/changelog @semantic-release/git @semantic-release/exec
  - pip install -U poetry
  - poetry install
stages:
  - name: release
    if: branch = master
jobs:
  include:
    # Define the release stage that runs semantic-release
    # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: semantic-release
