# https://docs.travis-ci.com/user/reference/xenial/
dist: xenial
env:
  global:
    - PRE_COMMIT_HOME=$HOME/.cache/pre-commit
    - TWINE_USERNAME=andreoliwa
cache:
  npm: true
  directories:
    - $HOME/.cache/pip
    - $PRE_COMMIT_HOME
# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.7"
script:
  # Run all pre-commit hooks on Travis.
  - pre-commit run --all-files
install:
  - pip install -U poetry pre-commit
  - poetry install --no-ansi --no-interaction
stages:
  - name: release
    if: branch = master
jobs:
  include:
    # Define the release stage that runs semantic-release
    # https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/travis.md
    - stage: release
      script: skip
      install:
        - pip install -U poetry pre-commit bumpversion twine
        - npm install -g semantic-release@15 @semantic-release/changelog @semantic-release/git @semantic-release/exec
      deploy:
        provider: script
        skip_cleanup: true
        script: semantic-release
