[tool.poetry]
name = "clit"
version = "0.9.0"
description = "Python CLI tools and scripts to help in everyday life"
authors = ["W. Augusto Andreoli <andreoliwa@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/andreoliwa/python-clit"
keywords = ["python3", "cli"]
# Trove classifiers
# Full list: https://pypi.python.org/pypi?%3Aaction=list_classifiers
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Plugins",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3 :: Only",
]

# TODO This is still not working properly; the scripts are created but not added to the PATH. Temporary workaround:
# Every time the scripts below change, run:
# xpoetry setup-py
[tool.poetry.scripts]
backup-full = "clit.files:backup_full"
docker-find = "clit.docker:docker_find"
docker-volume = "clit.docker:docker_volume"
git-local-prune = "clit.git:prune_local_branches"
git-vacuum = "clit.git:vacuum"
pycharm-cli = "clit.dev:pycharm_cli"
pypi = "clit.dev:pypi"
xpoetry = "clit.dev:extra_poetry"
xpostgres = "clit.db:extra_postgres"
xpytest = "clit.dev:extra_pytest"

[tool.poetry.dependencies]
python = "^3.6 || ^3.7"
argcomplete = "*"
click = "*"
colorlog = "*"
requests = "*"
SQLAlchemy = "*"
plumbum = "*"
prettyconf = "*"
requests-html = "*"

[tool.poetry.dev-dependencies]
coverage = "*"
docutils = "*"
flake8-nitpick = "*"
pytest-cov = "*"
pytest = "*"
Sphinx = "*"
tox = "*"
flake8-blind-except = "*"
flake8-bugbear = "*"
flake8-comprehensions = "*"
flake8-debugger = "*"
flake8-docstrings = "*"
flake8-isort = "*"
flake8-mypy = "*"
flake8-polyfill = "*"
flake8-pytest = "*"
flake8-quotes = "*"
pre-commit = {version = "*", allows-prereleases = true}
ipython = "*"
ipdb = "*"
pylint = "*"
mypy = "*"
black = {version = "*", allows-prereleases = true}

[tool.black]
line-length = 120
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

